dist: trusty
sudo: no

os: linux
language: c
compiler: gcc

matrix:
  fast_finish: true
  include:
    - compiler: ": Win32"
      env: IMAGEROOT=${HOME}/image-win32 CHOST=i686-w64-mingw32 CBUILD=x86_64-pc-linux-gnu
    - compiler: ": Win64"
      env: IMAGEROOT=${HOME}/image-win64 CHOST=x86_64-w64-mingw32 CBUILD=x86_64-pc-linux-gnu
  exclude:
    - compiler: gcc
    
addons:
  apt:
    packages:
      - gcc-mingw-w64
      - man2html
    
before_script:
    - unset CC; unset CXX

script:
    - cd generic && ./build
