sudo: required
dist: trusty

os: linux
language: cpp
compiler: gcc

matrix:
  fast_finish: true
  include:
    - compiler: ": Win32"
      env: IMAGEROOT=${HOME}/image-win32 CHOST=i686-w64-mingw32 CBUILD=x86_64-pc-linux-gnu
    - compiler: ": Win64"
      env: IMAGEROOT=${HOME}/image-win64 CHOST=x86_64-w64-mingw32 CBUILD=x86_64-pc-linux-gnu
  exclude:
    - compiler: gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y gcc-mingw-w64
    - sudo apt-get install -qq -y man2html
    
before_script:
    - unset CC; unset CXX

script:
    - cd openvpn-build/generic
    - ./build
